version: "2"
services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGPASSWORD
      - POSTGRES_DB
      - DATABASE_HOST
    ports:
      - "5432:5432"
